/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("io.netty:netty-all:4.1.17.Final")
    implementation("com.google.code.gson:gson:2.8.2")
    implementation("com.google.guava:guava:23.4-jre")
    implementation("commons-lang:commons-lang:2.6")
}

application {
    mainClass.set("com.elvarg.Server")
}

group = "Elvarg"
version = "1.0-SNAPSHOT"
description = "Elvarg-Game-Server"
java.sourceCompatibility = JavaVersion.VERSION_1_8

